apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
      - name: vue-container
        image: clippy:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 3000