apiVersion: v1
kind: Service
metadata:
  name: vue-app-service
spec:
  selector:
    app: vue-app
  type: NodePort
  ports:
    - port: 80         # Puerto interno del Service
      targetPort: 8080 # Puerto en el contenedor donde corre tu app
      nodePort: 30080  # Puerto en el nodo; debe estar en el rango 30000-32767
